name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Check out the repository code

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get install make  # Ensure 'make' is installed
        make install               # Install dependencies using the 'Makefile'

    - name: Run the application
      run: |
        make run > server_log.txt 2>&1 &   # Run the Flask app in the background

    - name: Wait for the server to start (polling)
      run: |
        for i in {1..10}; do
          echo "Checking if the server is up (attempt $i)..."
          if curl -s http://localhost:3000 > /dev/null; then
            echo "Server is up!"
            break
          fi
          echo "Server is not up yet. Waiting..."
          sleep 5
        done

    - name: Check if the server is running
      run: curl http://localhost:3000       # Check if the server is accessible

    - name: Print server log
      run: cat server_log.txt               # Print the server log for debugging
